// Customers actions.
export const LOAD_CUSTOMERS = 'LOAD_CUSTOMERS';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';

// Ui action
export const SET_FILTER_TEXT = 'SET_FILTER_TEXT';
export const TOGGLE_MODAL_DISPLAY = 'TOGGLE_MODAL_DISPLAY';
export const SET_MODAL_TYPE = 'SET_MODAL_TYPE';
export const SET_SELECTED_CUSTOMER = 'SET_SELECTED_CUSTOMER';